const AgiliteReactEnums = {
  reducers: {
    ADD_TAB: 'ADD_TAB',
    CHANGE_TAB: 'CHANGE_TAB',
    CLOSE_TAB: 'CLOSE_TAB',
    LEFT_MENU_OPEN: 'LEFT_MENU_OPEN',
    LEFT_MENU_CLOSE: 'LEFT_MENU_CLOSE',
    MENU_ITEM_CLICK: 'MENU_ITEM_CLICK',
    SIGN_IN_DESO: 'SIGN_IN_DESO',
    SIGN_OUT_DESO: 'SIGN_OUT_DESO',
    SET_PROFILE_DESO: 'SET_PROFILE_DESO',
    SET_DESO_DATA: 'SET_DESO_DATA'
  }
}

export default AgiliteReactEnums
